spring.application.name=UkrsteneReci
spring.jackson.deserialization.fail-on-null-for-primitives=false

server.address=0.0.0.0
server.port=${PORT:8081}

app.db.host=${DB_HOST:mysql-373b5ebe-ukrstene-reci.b.aivencloud.com}
app.db.port=${DB_PORT:11785}
app.db.name=${DB_NAME:ukrstene_reci}
app.db.username=${DB_USERNAME:avnadmin}
app.db.password=${DB_PASSWORD:}