const DEMO = {
  'Životinje':['MEDVED','LISICA','VRABAC','ZMIJA','JELEN','ZEKO','TIGAR','ORAO','RIBA','VUK','KONJ','BISON','PTICA','LASTA'],
  'Sport':['FUDBAL','KOSARKA','TENIS','PLIVANJE','ATLETIKA','BOKS','HOKEJ','ODBOJKA','RUKOMET','GOLF','TRKA','BICIKL'],
  'Hrana':['BUREK','CEVAP','SARMA','KAJMAK','AJVAR','PITA','PAPRIKA','PARADAJZ','KROMPIR','SIR','HLEB','MESO'],
  'Geografija':['BEOGRAD','DUNAV','SRBIJA','PLANINA','JEZERO','RIJEKA','TISA','BALKAN','DOLINA','MORE','GRAD','SAVA'],
  'Nauka':['ATOM','LASER','MAGNET','ENERGIJA','ELEKTRON','MOLEKUL','FIZIKA','BIOLOGIJA','HEMIJA','SILA'],
  'Muzika':['GITARA','KLAVIR','VIOLINA','BUBANJ','FLAUTA','NOTA','MELODIJA','RITAM','JAZZ','OPERA'],
  'Filmovi':['DRAMA','KOMEDIJA','AKCIJA','HOROR','ANIMACIJA','SCENA','GLUMA','FESTIVAL','NAGRADA'],
  'Istorija':['STEFAN','DUSAN','NEMANJA','KOSOVA','BITKA','SRBIJA','DINASTIJA','VOJVODA','BALKAN','CARSTVO'],
  'Tehnologija':['KOMPJUTER','INTERNET','SOFTVER','ROBOT','SERVER','MREZA','APLIKACIJA','PROGRAMER'],
};

const DIRS = [
  [0,1],[1,0],[0,-1],[-1,0],
  [1,1],[1,-1],[-1,1],[-1,-1]
];

const PALETTE = [
  '#ff4b6e','#00e5b4','#9b5de5','#ffc845',
  '#f97316','#22d3ee','#a3e635','#f472b6',
  '#fb923c','#4ade80','#c084fc','#38bdf8'
];