spring.application.name=UkrsteneReci
spring.jackson.deserialization.fail-on-null-for-primitives=false

server.address=0.0.0.0
server.port=${PORT:8081}

app.db.host=${DB_HOST:localhost}
app.db.port=${DB_PORT:3306}
app.db.name=${DB_NAME:ukrstene_reci}
app.db.username=${DB_USERNAME:root}
app.db.password=${DB_PASSWORD:}
app.db.ssl-mode=${DB_SSL_MODE:DISABLED}
app.db.pool-size=${DB_POOL_SIZE:5}
